spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 16379
      password: password
      timeout: 60000
      clientName: user-service
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/redis-spring
      username: taesu
      driver-class-name: org.h2.Driver
    url: ${spring.datasource.hikari.jdbc-url}
